### ISSUE TITLE
Add Long press / touch event on the tempo-control button to quickly change the bpm

### ISSUE THREAD

**Issue by gweesin** [heybran/guitar-metronome#5]
I am a beginner in music, and I'm not sure if I will need to quickly adjust the tempo in the future. However, when I want to explore these features, I would like to be able to adjust the BPM quickly to understand its specific effects. So, it would be great to have a functionality for quick adjustment by long-pressing.

**Comment by heybran** [comment]
Absolutely, it will definitely improve the user experience quite a lot. Once this feature is implemented, I think we can also throw in a slider to adjust the tempo easily as I've seen some other online metronomes do that. I assume you'd like to work on this long-pressing features yeah?

**Comment by gweesin** [comment]
> Absolutely, it will definitely improve the user experience quite a lot. Once this feature is implemented, I think we can also throw in a slider to adjust the tempo easily as I've seen some other online metronomes do that. I assume you'd like to work on this long-pressing features yeah?

exactly, I'm so glad if you assign to me.

**Comment by heybran** [comment]
@gweesin Not sure what it looks like to you, but it seems to me there is a tiny bug. Here's steps to replicate:

1. Visit: https://guitar-metronome.netlify.app/
2. Press down `+` button until tempo reaches aound 144 BPM
3. Then release mouse, now click `+` button (not press), BPM gets incremented by `2` instead of default `1`.

Please let me know what you found. Thanks

**Comment by gweesin** [comment]
Thanks for your professional. We also need reset `#triggerCount` on handleMouseUp callback
